---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-default
    image: molecule-default
    dockerfile: ./Dockerfile
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
